// <auto-generated />
using System;
using EntityFramework1;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EntityFramework1.Migrations
{
    [DbContext(typeof(SchoolDbContext))]
    [Migration("20190915144323_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EntityFramework1.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Birthdate");

                    b.Property<string>("Name");

                    b.Property<int>("Studnr");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new { Id = 1, Birthdate = new DateTime(2000, 5, 18, 0, 0, 0, 0, DateTimeKind.Unspecified), Name = "Bart", Studnr = 1001 },
                        new { Id = 2, Birthdate = new DateTime(1997, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified), Name = "Suzanne", Studnr = 1002 },
                        new { Id = 3, Birthdate = new DateTime(1999, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), Name = "Sam", Studnr = 1003 },
                        new { Id = 4, Birthdate = new DateTime(2001, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified), Name = "Inge", Studnr = 1004 }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
